#!/bin/bash
# Run this in Claude Code from smorch-brain root to sync the clean plugin builds
# Generated by Cowork session - March 25, 2026

BRAIN="$(pwd)"

echo "=== Syncing eo-microsaas-os ==="
# Remove duplicates from source
rm -rf "$BRAIN/plugins/eo-microsaas-os/skills/gtm-fitness-scoring-engine"
rm -rf "$BRAIN/plugins/eo-microsaas-os/skills/icp-clarity-scoring-engine"
rm -rf "$BRAIN/plugins/eo-microsaas-os/skills/market-attractiveness-scoring-engine"
rm -rf "$BRAIN/plugins/eo-microsaas-os/skills/project-definition-scoring-engine"
rm -rf "$BRAIN/plugins/eo-microsaas-os/skills/strategy-selector-engine"
rm -rf "$BRAIN/plugins/eo-microsaas-os/skills/eo-gtm-asset-builder"
rm -f  "$BRAIN/plugins/eo-microsaas-os/commands/eo-score.md"

# Update plugin.json to v3.1.0
cat > "$BRAIN/plugins/eo-microsaas-os/.claude-plugin/plugin.json" << 'EOF'
{
  "name": "eo-microsaas-os",
  "version": "3.1.0",
  "description": "EO MicroSaaS Operating System with Training Guide. Walks entrepreneurs from idea to live product through a gated 6-step journey. Includes pedagogical guide (/eo-guide) that maps training modules to hands-on actions, plus technical skills for brain ingestion, GTM assets, architecture, and full-stack development.",
  "author": {
    "name": "Mamoun Alamouri / SMOrchestra.ai"
  }
}
EOF
echo "  Removed 6 duplicate skills, 1 duplicate command, bumped to v3.1.0"

echo ""
echo "=== Syncing smorch-gtm-engine ==="
# Remove moved skills
rm -rf "$BRAIN/plugins/smorch-gtm-engine/skills/clay-operator"
rm -rf "$BRAIN/plugins/smorch-gtm-engine/skills/ghl-operator"
rm -rf "$BRAIN/plugins/smorch-gtm-engine/skills/heyreach-operator"
rm -rf "$BRAIN/plugins/smorch-gtm-engine/skills/instantly-operator"
rm -rf "$BRAIN/plugins/smorch-gtm-engine/skills/n8n-architect"
rm -f  "$BRAIN/plugins/smorch-gtm-engine/.mcp.json"

# Update plugin.json to v2.0.0
cat > "$BRAIN/plugins/smorch-gtm-engine/.claude-plugin/plugin.json" << 'EOF'
{
  "name": "smorch-gtm-engine",
  "version": "2.0.0",
  "description": "Signal-to-Trust GTM campaign engine. Strategy, positioning, signals, wedges, asset generation, outbound orchestration, and campaign management. Run /launch-campaign to start.",
  "author": {
    "name": "Mamoun Alamouri",
    "homepage": "https://smorchestra.ai"
  }
}
EOF
echo "  Removed 5 moved skills, bumped to v2.0.0"
echo ""
echo "NOTE: Skill CONTENT was already synced from deployed by the earlier Claude Code session."
echo "This script only removes the duplicates and bumps versions."
echo ""
echo "Run 'git add -A && git commit -m \"Clean duplicate skills, bump versions\"' to commit."
