-- Migration 002: Leads & Entity Tables
-- leads, company_entities, individual_entities, influencer_entities,
-- tenant_leads, enrichment_results, enrichment_logs, lead_scores_history

CREATE TABLE IF NOT EXISTS public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  external_id varchar(500),
  source_hash varchar(100),
  lead_type varchar(50),
  scraper_type varchar(50),
  platform varchar(50),
  name varchar(255) NOT NULL,
  email varchar(255),
  phone varchar(20),
  company_id uuid,
  campaign_id uuid[],
  fit_score numeric,
  engagement_score numeric DEFAULT 0,
  priority_class varchar(1),
  fit_score_at_scrape numeric,
  enrichment_version varchar(20),
  reply_count integer DEFAULT 0,
  engagement_count integer DEFAULT 0,
  last_engagement_at timestamp,
  is_duplicate boolean DEFAULT false,
  duplicate_of_id uuid REFERENCES leads(id) ON DELETE SET NULL,
  raw_data jsonb,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),
  deleted_at timestamp,
  company_name text,
  lead_role text,
  industry text,
  run_id uuid,
  hiring_signals smallint,
  growth_signals integer,
  role_fit_signal integer,
  industry_fit_signal integer,
  geo_fit_signal integer,
  location varchar,
  PRIMARY KEY (id),
  UNIQUE (tenant_id, external_id, source_hash)
);

CREATE TABLE IF NOT EXISTS public.company_entities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  company_name varchar(255) NOT NULL,
  website varchar(500),
  industry varchar(100),
  company_size varchar(50),
  country varchar(50),
  state_province varchar(100),
  city varchar(100),
  address text,
  main_email varchar(255),
  main_phone varchar(20),
  linkedin_url varchar(500),
  facebook_url varchar(500),
  twitter_url varchar(500),
  google_maps_rating numeric,
  review_count integer,
  apify_metadata jsonb,
  source_url text,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),
  category text,
  email text,
  google_maps_url varchar,
  google_place_id text,
  latitude text,
  longitude text,
  phone text,
  platform text,
  postal_code text,
  rating real,
  state text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.individual_entities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  company_id uuid REFERENCES company_entities(id) ON DELETE SET NULL,
  first_name varchar(100),
  last_name varchar(100),
  job_title varchar(255),
  department varchar(100),
  email varchar(255),
  phone varchar(20),
  linkedin_url varchar(500),
  linkedin_profile_id varchar(100),
  is_decision_maker boolean,
  decision_maker_level varchar(50),
  seniority_level varchar(50),
  apify_metadata jsonb,
  source_url text,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.influencer_entities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  platform varchar(50) NOT NULL,
  handle varchar(255),
  display_name varchar(255),
  bio text,
  profile_url varchar(500),
  profile_image_url varchar(500),
  youtube_followers integer,
  youtube_subs_formatted varchar(50),
  instagram_followers integer,
  tiktok_followers integer,
  facebook_followers integer,
  twitter_followers integer,
  linkedin_followers integer,
  twitch_followers integer,
  medium_followers integer,
  substack_subscribers integer,
  custom_followers integer,
  engagement_rate numeric,
  engagement_rate_platform_specific jsonb,
  avg_views_per_video integer,
  avg_likes_per_post integer,
  video_count integer,
  post_count integer,
  topic_category varchar(100),
  primary_language varchar(10),
  content_quality_score numeric,
  verified boolean,
  verification_type varchar(50),
  email varchar(255),
  phone varchar(20),
  contact_email varchar(255),
  website varchar(500),
  discovered_via varchar(100),
  referral_source varchar(255),
  apify_metadata jsonb,
  source_url text,
  is_brand_ambassador boolean,
  has_manager boolean,
  manager_email varchar(255),
  last_updated timestamp,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tenant_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  attached_at timestamptz NOT NULL DEFAULT now(),
  source_run_id uuid,
  PRIMARY KEY (id),
  UNIQUE (tenant_id, lead_id)
);

CREATE TABLE IF NOT EXISTS public.enrichment_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  layer1_gemini jsonb NOT NULL,
  layer2_relevance jsonb NOT NULL,
  layer3_authority jsonb NOT NULL,
  scoring jsonb NOT NULL,
  class_rating varchar(1),
  recommended_hook_id varchar(10),
  recommended_dialect varchar(50),
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),
  enrichment_version varchar(20),
  final_priority_score numeric,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.enrichment_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  enrichment_result_id uuid REFERENCES enrichment_results(id) ON DELETE SET NULL,
  layer integer,
  layer_name varchar(50),
  status varchar(50),
  started_at timestamp,
  completed_at timestamp,
  duration_ms integer,
  api_provider varchar(50),
  api_model varchar(100),
  tokens_used integer,
  cost_cents integer,
  error_message text,
  error_code varchar(50),
  retry_count integer DEFAULT 0,
  created_at timestamp DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lead_scores_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  campaign_id uuid,
  fit_score numeric,
  engagement_score numeric,
  total_score numeric,
  score_reason varchar(100),
  created_at timestamp DEFAULT now(),
  PRIMARY KEY (id)
);
