#!/usr/bin/env bash
# create-pr.sh — Create a GitHub PR for a completed task
# Deploy to: smo-brain at /root/.smo/queue/create-pr.sh
# Usage: ./create-pr.sh TASK-XXX ["summary"] ["label"]

set -euo pipefail

QUEUE_DB="/root/.smo/queue/queue.db"
LOG_DIR="/root/.smo/logs"

# Load parameterized SQL wrapper (Sprint 1, Fix #1 — SQL injection prevention)
source "$(dirname "$0")/db.sh"

TASK_ID="${1:-}"
SUMMARY="${2:-}"
EXTRA_LABEL="${3:-}"

if [[ -z "$TASK_ID" ]]; then
  echo "Usage: ./create-pr.sh TASK-XXX [summary] [label]"
  exit 1
fi

mkdir -p "$LOG_DIR"

log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] [create-pr] $1"
  echo "$msg"
  echo "$msg" >> "$LOG_DIR/create-pr.log"
}

# ─── LOAD TASK ───

TASK_JSON=$(db_query_json "SELECT * FROM tasks WHERE id = :1 LIMIT 1" "$TASK_ID")
REPO=$(echo "$TASK_JSON" | jq -r '.[0].repo')
BRANCH=$(echo "$TASK_JSON" | jq -r '.[0].branch')
TITLE=$(echo "$TASK_JSON" | jq -r '.[0].title')
GOAL=$(echo "$TASK_JSON" | jq -r '.[0].goal')
ROLE=$(echo "$TASK_JSON" | jq -r '.[0].role')
TIER=$(echo "$TASK_JSON" | jq -r '.[0].tier // "unknown"')
SCORE=$(echo "$TASK_JSON" | jq -r '.[0].quality_score // "N/A"')
SERVER_NODE=$(echo "$TASK_JSON" | jq -r '.[0].server_node')
DECLARED_FILES=$(echo "$TASK_JSON" | jq -r '.[0].declared_files // "[]"')

log "Creating PR for $TASK_ID on $REPO ($BRANCH)"

# ─── DETERMINE RISK TIER ───

RISK="LOW"
FILES_JSON=$(echo "$DECLARED_FILES" | jq -r '.[]' 2>/dev/null || echo "")
for f in $FILES_JSON; do
  case "$f" in
    *auth*|*payment*|*migration*|*infra*|*.env*)
      RISK="HIGH"
      break
      ;;
    *api*|*config*|*middleware*|*database*)
      [[ "$RISK" != "HIGH" ]] && RISK="MEDIUM"
      ;;
  esac
done

# ─── BUILD PR LABELS ───

LABELS="agent-pr,role:$ROLE,tier:$TIER,risk:$RISK"
[[ -n "$EXTRA_LABEL" ]] && LABELS="$LABELS,$EXTRA_LABEL"

# Ensure labels exist (create silently if not)
IFS=',' read -ra LABEL_ARRAY <<< "$LABELS"
for label in "${LABEL_ARRAY[@]}"; do
  gh label create "$label" --repo "$REPO" --color "0E8A16" --force 2>/dev/null || true
done

# ─── BUILD PR BODY ───

PR_BODY="## $TASK_ID: $TITLE

### Goal
$GOAL

### Details
| Field | Value |
|-------|-------|
| Role | \`$ROLE\` |
| Node | \`$SERVER_NODE\` |
| Tier | \`$TIER\` |
| Quality Score | **$SCORE / 10** |
| Risk | **$RISK** |

### Files Changed
$DECLARED_FILES

### Summary
${SUMMARY:-Auto-generated by SMOrchestra AI Agent Queue}

---
*Generated by SMOrchestra AI-Native Organization*
*Agent: $ROLE on $SERVER_NODE | Task: $TASK_ID*"

# ─── CREATE PR ───

PR_URL=$(gh pr create \
  --repo "$REPO" \
  --base main \
  --head "$BRANCH" \
  --title "[$TASK_ID] $TITLE" \
  --body "$PR_BODY" \
  --label "$LABELS" \
  2>&1) || {
    log "ERROR: Failed to create PR: $PR_URL"
    db_update_task "$TASK_ID" "status" "failed"
    local err_msg
    err_msg=$(echo "$PR_URL" | head -1 | sed "s/[^a-zA-Z0-9 .,;:!?()/-]//g" | cut -c1-200)
    audit "$TASK_ID" "pr_failed" "{\"error\": \"$err_msg\"}"
    exit 1
  }

log "PR created: $PR_URL"

# ─── UPDATE TASK ───

db_update_task "$TASK_ID" "status" "pr_open"
db_update_task "$TASK_ID" "pr_url" "$PR_URL"

audit "$TASK_ID" "pr_created" "{\"url\": \"$PR_URL\", \"risk\": \"$RISK\", \"labels\": \"$LABELS\"}"

# ─── AUTO-MERGE LOW RISK ───

if [[ "$RISK" == "LOW" ]] && [[ -z "$EXTRA_LABEL" ]]; then
  log "LOW risk + no quality issues — enabling auto-merge"
  gh pr merge "$PR_URL" --auto --squash --repo "$REPO" 2>/dev/null || \
    log "WARNING: Auto-merge not available (branch protection may not support it)"
fi

# ─── RECORD ARTIFACTS ───

for f in $FILES_JSON; do
  db_add_artifact "$TASK_ID" "modified_file" "$f" "$(echo "$SUMMARY" | head -1)"
done

# Proactive CEO notification for HIGH/MEDIUM risk PRs (Sprint 1, Fix #3)
if [[ "$RISK" != "LOW" ]] || [[ -n "$EXTRA_LABEL" ]]; then
  "$(dirname "$0")/notify-ceo.sh" "pr_ready" "$TASK_ID" 2>/dev/null &
fi

echo "{\"task_id\": \"$TASK_ID\", \"pr_url\": \"$PR_URL\", \"risk\": \"$RISK\", \"score\": \"$SCORE\"}"
