// DOCX Builder v2 — Per-customer brand colors
// Renders MD blueprints into branded Word documents

const fs = require('fs');
const path = require('path');
const {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  Table, TableRow, TableCell, WidthType, BorderStyle,
  AlignmentType, ShadingType,
} = require('docx');
const { parseBlueprint } = require('../utils/md-parser');

/**
 * Build a DOCX from a markdown blueprint
 * @param {string} inputPath - Path to MD file
 * @param {string} outputDir - Output directory
 * @param {object} brand - Brand config with docxColors, fonts
 */
async function buildDocx(inputPath, outputDir, brand) {
  const blueprint = parseBlueprint(inputPath);
  const children = [];
  const dc = brand.docxColors;
  const fonts = brand.fonts;

  // Title
  children.push(
    new Paragraph({
      children: [new TextRun({ text: blueprint.title, bold: true, size: 36, color: dc.dark, font: fonts.en })],
      heading: HeadingLevel.TITLE,
      spacing: { after: 100 },
    })
  );

  // Brand accent line
  children.push(
    new Paragraph({
      children: [new TextRun({ text: '                              ', color: dc.primary })],
      border: { bottom: { color: dc.primary, size: 6, style: BorderStyle.SINGLE } },
      spacing: { after: 300 },
    })
  );

  // Process sections
  for (const section of blueprint.sections) {
    const headingLevel = section.level === 2 ? HeadingLevel.HEADING_1 : HeadingLevel.HEADING_2;
    children.push(
      new Paragraph({
        children: [new TextRun({
          text: section.title,
          bold: true,
          size: section.level === 2 ? 28 : 24,
          color: section.level === 2 ? dc.primary : dc.dark,
          font: fonts.en,
        })],
        heading: headingLevel,
        spacing: { before: 300, after: 120 },
      })
    );

    if (section.text) {
      const paragraphs = section.text.split('\n').filter(l => l.trim());
      for (const para of paragraphs) {
        children.push(buildParagraph(para, dc, fonts));
      }
    }

    for (const table of section.tables) {
      children.push(buildTable(table, dc, fonts));
      children.push(new Paragraph({ spacing: { after: 200 } }));
    }

    for (const list of section.lists) {
      for (const item of list) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: item, size: 22, font: fonts.en, color: dc.text })],
            bullet: { level: 0 },
            spacing: { after: 60 },
          })
        );
      }
      children.push(new Paragraph({ spacing: { after: 120 } }));
    }
  }

  // Footer with brand accent
  children.push(
    new Paragraph({
      children: [new TextRun({
        text: blueprint.metadata.footer || 'Generated by EO GTM Asset Factory',
        size: 16, color: dc.secondary, font: fonts.en, italics: true,
      })],
      spacing: { before: 600 },
      border: { top: { color: dc.primary, size: 2, style: BorderStyle.SINGLE } },
    })
  );

  const doc = new Document({
    styles: {
      default: {
        document: {
          run: { font: fonts.en, size: 22, color: dc.text },
          paragraph: { spacing: { line: 360 } },
        },
      },
    },
    sections: [{ children }],
  });

  const buffer = await Packer.toBuffer(doc);
  const filename = path.basename(inputPath, '.md') + '.docx';
  const outputPath = path.join(outputDir, filename);
  fs.writeFileSync(outputPath, buffer);

  return { file: filename, type: 'docx', size: buffer.length };
}

function buildParagraph(text, dc, fonts) {
  const runs = [];
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  for (const part of parts) {
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({
        text: part.slice(2, -2),
        bold: true, size: 22, font: fonts.en, color: dc.dark,
      }));
    } else if (part.trim()) {
      runs.push(new TextRun({
        text: part, size: 22, font: fonts.en, color: dc.text,
      }));
    }
  }
  return new Paragraph({ children: runs, spacing: { after: 120 } });
}

function buildTable(tableData, dc, fonts) {
  const rows = [];

  rows.push(
    new TableRow({
      children: tableData.headers.map(h =>
        new TableCell({
          children: [new Paragraph({
            children: [new TextRun({ text: h, bold: true, size: 20, color: 'FFFFFF', font: fonts.en })],
          })],
          shading: { fill: dc.dark, type: ShadingType.SOLID },
          width: { size: Math.floor(100 / tableData.headers.length), type: WidthType.PERCENTAGE },
        })
      ),
    })
  );

  tableData.rows.forEach((row, idx) => {
    rows.push(
      new TableRow({
        children: row.map(cell =>
          new TableCell({
            children: [new Paragraph({
              children: [new TextRun({ text: cell, size: 20, font: fonts.en, color: dc.text })],
            })],
            shading: idx % 2 === 0 ? { fill: dc.cream || 'FDF8F0', type: ShadingType.SOLID } : undefined,
          })
        ),
      })
    );
  });

  return new Table({ rows, width: { size: 100, type: WidthType.PERCENTAGE } });
}

module.exports = { buildDocx };
